### ISSUE TITLE
Update to .Net Core / .Net

### ISSUE THREAD

**Issue by mdawsonuk** [CSSS-Games/CSSS#10]
As there are no GitHub Actions for .Net Framework, for #9 to be completed, the .Net version must first be upgraded

**Comment by mdawsonuk** [comment]
There is no upgrade path to .Net Core from .Net Framework, so I'll be targeting .Net 6.0 as that's the current LTS version, then the upgrade to .Net 8.0 can be done when it is released later this year - that comes with the advantage of three years of support.

**Comment by stuajnht** [comment]
Closed with merge of #12
